leptonai/leptonai

leptonai/photon/photon.py
leptonai/photon/tests/test_photon_cli.py

Closes: #33
```
$ lep photon create -n test -m nonexistent.py
Failed to create photon: 'nonexistent.py' is neither an existing file nor an importable python variable
```

fix: error msg when passing nonexisting file to photon create command

---

leptonai/photon/photon.py

This allows the user to have some idea about how to use the service.
```
(lepton) ➜  sdk git:(yqcli) lep photon run -n gpt2 -m hf:gpt2 --local                    Rebuilding photon with --model hf:gpt2.
If you want to run without rebuilding, please remove the --model arg.
Photon gpt2 created.
Launching photon on port: 8080
2023-09-15 00:07:39.674 | INFO     | leptonai.photon.hf.hf:pipeline:167 - Creating pipeline for text-generation(model=gpt2, revision=11c5a3d5).
HuggingFace download might take a while, please be patient...
2023-09-15 00:07:55,349 - INFO:  
If you are using standard photon, a few urls that may be helpful:
- http://0.0.0.0:8080/docs OpenAPI documentation
- http://0.0.0.0:8080/redoc Redoc documentation
- http://0.0.0.0:8080/openapi.json Raw OpenAPI schema
- …
```

feat(cli): print more helpful client note

---

leptonai/api/workspace.py

Manually tested:
```
In [1]: from leptonai import api
In [2]: api.workspace.version()
Out[2]: (0, 10, 3)
```

fix(sdk): minor bug in version checking (embarrassing)

---

.github/workflows/release.yaml
.github/workflows/test-cp310.yaml
.github/workflows/test-cp38.yaml
CONTRIBUTING.md
README.md
leptonai/photon/hf/hf.py
leptonai/photon/hf/hf_utils.py

Since this actually is the main repo and not a sdk.

chore: rename repo from leptonai-sdk to leptonai

---

leptonai/cli/photon.py
leptonai/client.py
leptonai/cloudrun/remote.py
leptonai/cloudrun/tests/test_cloudrun.py
leptonai/config.py
leptonai/photon/prebuilt/echo.py

Per offline discussion - this allows a more efficient usage for development use cases by avoiding dangling deployments.

feat(sdk): set default timeout to 1 hour for all deployments

---

leptonai/client.py

tested:
```
from leptonai.client import Client
import base64
c = Client("https://aiqr.lepton.run")
```
and confirmed that there are no error debug messages.

fix(client): ignore path '/'

---

requirements.txt

there is a new version of cloudpickle released today, we have run into errors in e2e tests when local cloudpickle version is new (3.0.0) and remote cloudpickle version is old (2.2.1).
```
got /opt/lepton/venv/bin/lep
Failed to launch photon: Can't get attribute '_class_setstate' on <module
'cloudpickle.cloudpickle' from
'/opt/lepton/venv/lib/python3.10/site-packages/cloudpickle/cloudpickle.py'>
```
Not sure if it's an issue in new version of it's a version mismatch. Pin to old version for now to unbreak.

Pin cloudpickle version to 2.2.1

---

leptonai/photon/background.py
leptonai/photon/batcher.py
leptonai/photon/photon.py
leptonai/photon/tests/test_photon.py
leptonai/photon/tests/test_photon_concurrency.py
leptonai/photon/tests/utils.py
leptonai/util/__init__.py
leptonai/util/util.py

In the past, when we do
```
@Photon.handler
def foo(self):
...
```
The code runs in the main uvicorn event loop, and blocks the uvicorn server (during which time basic things like "/openapi.json" and "healthz" are not accessible).
This PR adds two functionalities:
- All endpoints defined in @Photon.handler, when deployed, now run in a separate thread, so the uvicorn main event loop is not blocked.
- In default, the number of endpoint calls being run concurrently is 1, which is the same as before. With `handler_max_concurrency`, one can control the concurrency so that multiple endpoints can be run at the same time in different thread. NOTE THAT, the photon framework does not guarantee thread safety of user code - lepton's scaffolding code is thread safe, but any user code's thread safety …

feat(sdk): make all @Photon.handler calls async in its own pool.

---

leptonai/photon/photon.py

since task has been "partialed", all the arguments are printed if we print task

fix: only print background task name in debug log

---

leptonai/cli/photon.py

This is sometimes helpful especially when the python library depends on some system libraries. For example, strictly speaking python ffmpeg requires system ffmpeg installed, although the pip install does not check. This makes the order right.

chore(sdk): install system dependency before pip

---

leptonai/photon/__init__.py
leptonai/photon/types/__init__.py
leptonai/photon/types/util.py

Added the following utility functions:
- Added a parameter `return_file` to the `get_file_content` function to return a file-like object. This is useful when e.g. opencv requires a file rather than string or byteio.
- Added a `make_png_response` utility function to return a PIL Image. In theory, we might be able to just allow users to return a PIL image and automatically convert that to a PNGResponse, but we can do that later.

feat(sdk): utility functions for images

---

leptonai/photon/base.py
leptonai/photon/photon.py
leptonai/photon/tests/test_sdk.py

This avoids users to accidentally specify `name` and `model` member variables in their photons.
This does not incur any functional change to any existing photon, other than display issues (like `model` becoming the user's object instead of the model string).

fix(sdk): rename self.name and self.model to names with underscore

---

leptonai/photon/photon.py
leptonai/photon/tests/test_photon_raw_args.py
requirements.txt

This is particularly useful if one wants to handle files etc.

feat(sdk): allow passing use_raw_args=True to Photon.handler to not wrap args in json but directly to fastapi

---

leptonai/config.py
leptonai/photon/photon.py
leptonai/photon/tests/test_photon.py

```py
from leptonai import Photon
class CustomImage(Photon):
image = "a:b"
exposed_port = 8765
cmd = ["python", "-m", "http.server", str(exposed_port)]
```
metadata.json:
```
{
...
"image": "a:b",
"exposed_port": 8765,
"cmd": [
"python",
"-m",
"http.server",
"8765"
]
...
}
```

feat: add fields in photon metadata.json to support running custom image

---

leptonai/api/types.py
leptonai/cli/photon.py
leptonai/config.py
leptonai/photon/photon.py
leptonai/photon/prebuilt/template.py
leptonai/photon/tests/test_photon.py
leptonai/photon/vllm/vllm.py

Also in the comments field of the source file:

feat(sdk): Add deployment_template to photon

---

leptonai/cli/photon.py
leptonai/photon/photon.py
leptonai/photon/tests/test_photon.py

`__init__` is called in photon creation time as well, which would trigger an error. Added tests to guard the bug.

fix(sdk): do not set env and secret in __init__ but in init

---

leptonai/api/workspace.py
leptonai/cli/deployment.py
leptonai/cli/secret.py
leptonai/cli/workspace.py

This allows one to programmaticly log in with workspace id and workspace token, so inside deployments one can use functionalities like queue and kv.

feat(sdk): add api.workspace.login() function

---

leptonai/photon/photon.py
leptonai/photon/tests/test_photon_init_lock.py

This allows us to run warmup handler calls inside init - useful if some of the functionalities, like torch.compile, requires an actual run to warm up.

fix(sdk): set _init_called before running init()

---

leptonai/photon/base.py
leptonai/photon/hf/hf.py
leptonai/photon/tests/test_sdk.py
leptonai/photon/util.py

using hf model id is still supported
this is for trimming down dependencies in environment that don't need to run photons

drop support of creating photon from hf model and pipeline runtime instance

---

requirements.txt

We use `timeout_graceful_shutdown` in our codebase. It is introduced in https://github.com/encode/uvicorn/pull/1950
Earlier versions will show this exception:
```
Failed to launch photon: <class 'TypeError'>: Config.__init__() got an unexpected keyword 
argument 'timeout_graceful_shutdown'
Traceback:
Traceback (most recent call last):
File "/home/jiayq/Documents/code/lepton/sdk/leptonai/cli/photon.py", line 669, in run
photon.launch(port=port)
File "/home/jiayq/Documents/code/lepton/sdk/leptonai/photon/photon.py", line 841, in launch
self._uvicorn_run(
File "/home/jiayq/Documents/code/lepton/sdk/leptonai/photon/photon.py", line 755, in 
_uvicorn_run
config = uvicorn.Config(
TypeError: Config.__init__() got an unexpected keyword argument 'timeout_graceful_shutdown'
```

fix(sdk): pin uvicorn version to be >=0.22.0

---

leptonai/api/connection.py

To use this, do
```
export LEPTON_DEBUG_HEADERS="X-my-header-name=my-header-value"
```
and run with your normal lepton cli commands.

feat(cli): allow additional headers to be specified in LEPTON_DEBUG_HEADERS

---

leptonai/api/job.py
leptonai/api/types.py
leptonai/cli/cli.py
leptonai/cli/job.py

Tried with the following test.json job file:
```
{
"resource_shape": "cpu.small",
"container": {
"image": "python:3.11-slim",
"command": ["python", "--version"]
},
"completions": 1,
"parallelism": 1
}
```
Since the job config is a bit too much for the cli to write, I am letting the CLI take a file rather than using a bunch of args.

feat(sdk): initial support for job api

---

requirements.txt

```bash
cd ${HOME}/leptonai
pip install -e .
lep photon run -h
```
will fail:
```
Traceback (most recent call last):
File "/Users/leegyuho/anaconda3/bin/lep", line 5, in <module>
from leptonai.cli import lep
File "/Users/leegyuho/leptonai/leptonai/__init__.py", line 6, in <module>
from .cloudrun import Remote
File "/Users/leegyuho/leptonai/leptonai/cloudrun/__init__.py", line 14, in <module>
from .remote import Remote, clean
File "/Users/leegyuho/leptonai/leptonai/cloudrun/remote.py", line 17, in <module>
from leptonai.photon import Photon
File "/Users/leegyuho/leptonai/leptonai/photon/__init__.py", line 6, in <module>
from .photon import (  # noqa: F401
File "/Users/leegyuho/leptonai/leptonai/photon/photon.py", line 66, in <module>
from leptonai.util.cancel_on_disconnect import …
```

fix(requirements): add missing "exceptiongroup"

---

leptonai/photon/__init__.py
leptonai/photon/photon.py
leptonai/photon/tests/test_worker.py
leptonai/photon/worker.py

```python
from leptonai.photon import Worker
class MyWorker(Worker):
def on_task(self, x: int):
time.sleep(5):
return x * 2
```
POST /task {"x": 1} -> returns a task id
GET /task?task_id -> returns status (&& result if configured save_result=True) of the corresponding task

feat: Add Worker skeleton for task queue type of workload

---

leptonai/api/photon.py
leptonai/photon/photon.py
leptonai/photon/tests/test_photon.py

This is because in some cases, like running LLMs, some secrets are optional - like one may or may not need the `HUGGING_FACE_HUB_TOKEN` secret, depending on whether the specific model is behind an authentication wall. We will use deployment template as a guidance but not a strict rule as a result, and let the user specify what to do.

fix(sdk): when env and secret in dep template are not set, issue warning rather than exception

---

leptonai/config.py
leptonai/photon/photon.py
leptonai/photon/tests/test_photon_auth.py

To use, do
```python
config.set_local_deployment_token("sdfakdsjfj")
```
or set the env variable in shell
```shell
export LEPTON_LOCAL_DEPLOYMENT_TOKEN="sdfakdsjfj"
```
Note that local deployment token is ignored when deployed on the lepton platform.

feat(sdk): add local authentication

---

leptonai/tests/shell/README.md
leptonai/tests/shell/shell.py

Reverts leptonai/leptonai#195
The file is actually used in internal e2e test. Leaving it as-is and not deleting.

Revert "chore(sdk): Remove dangling testing file"

---

.github/workflows/docker.yaml
leptonai/config.py
leptonai/photon/dockerfiles/photon-rocm-py.Dockerfile
leptonai/photon/dockerfiles/photon-rocm-runner.Dockerfile
leptonai/tests/test_configs.py

Formally platiform-fy the image for non-first-party usage as well.
To avoid rebuilding and pushing base images that are too big, I added two options: `build_rocm_base` and `is_rocm_release`.
- The first time we push, we will need to build rocm base as it is a new base image.
- For all future builds, rocm and the default will be two parallel build and releases, but we likely will sync them as well.

feat(sdk): rocm docker

---

leptonai/photon/tests/test_types_file.py
leptonai/photon/types/file.py

pydantic 1.x doesn't have smart union set to true, and will coerce str into bytes. This fixes the problem.
Also added a copy contructor capability.

fix(sdk): bug from pydantic 1.x

---

leptonai/api/photon.py
leptonai/photon/base.py

We rely on the implicit assumption taht find_local_photon() will return the path of the local photon, but this is only true when the photon is created locally. If the photon is downloaded via `lep photon fetch`, then record[0] is the real id and not the path - this PR fixes it by returning the actual path.

fix(sdk): allow find_local_photon to return the actual path, and not id

---

leptonai/client.py
requirements.txt

In theory this shouldn't have an issue and test passed - @xiang90 ptal
Or should we keep it False in default?

chore(sdk): enable h2 in default in clients

---

leptonai/photon/tests/test_photon_concurrency.py

This avoid flaky test results affecting PR landing like #293 .

chore(test): relax test time constraint

---

leptonai/client.py
leptonai/photon/tests/test_client.py

In the past, if an endpoint is mounted as "/", client cannot invoke it other than explicitly using web endpoint get or put. This makes "/" mounted on `__call__`.

chore(sdk): fix client bug

---

leptonai/cli/kv.py
leptonai/kv.py

An internal PR https://github.com/leptonai/lepton/pull/5975 changed the return format of KV api, so we need to now access ["metadata"]["name"] instead of ["name"].

fix(sdk): fix KV api json access

---

leptonai/config.py
leptonai/photon/photon.py

This accompanies https://github.com/leptonai/lepton/pull/6028 - allowing us to deploy photons with configurable timeouts by setting env variable LEPTON_TIMEOUT_GRACEFUL_SHUTDOWN and LEPTON_INCOMING_TRAFFIC_GRACE_PERIOD.

feat(sdk): make graceful timeout configurable by package-level defaults

---

leptonai/config.py

This is continuing the pull request #323 - on the platform, 250 seconds is usually enough for the envoy to fully update its routing.

feat(sdk): set graceful timeoout default for on-platform deployments

---

leptonai/cli/job.py
leptonai/templates/whisperx/whisperx.py

closes #325 .
After this, you can pass in `language=""` to ask the model to do language autodetect.

fix(whisperx): allow passing in empty string for language auto-detection, and keep default to English.

---

requirements.txt

Reverts leptonai/leptonai#211 . This fixes #321 , and if we want faster download, one can manually install hf-transfer.
closes #321

Revert "pre-install hf-transfer for faster download"

---

leptonai/cli/objectstore.py

This is also backward compatible in case some workspaces do not have last modified time yet.

feat(cli): add last modified time in object store

---

leptonai/client.py
leptonai/photon/photon.py
leptonai/photon/tests/test_client.py

Closes: #5004
If there is a path name, say "/run", with multiple methods specified, we will:
- use "post" as the default method, so client.run() always calls post
- allow user to specify the method, like client.run.post() and client.run.get().
See the test file for details.

feat(sdk): add http method to openapi schema, and added client support multiple methods for a path.

---

leptonai/cli/pod.py
leptonai/photon/tests/test_photon.py

fix: pod creation

---

leptonai/api/types.py

In the long run we will make all APIs up to date - but this fixes a temp issue for a client.

fix(cli/api): make the Mount spec up to date with backend

---

leptonai/api/kv.py
leptonai/api/v1/kv.py
leptonai/cli/kv.py
leptonai/kv.py
leptonai/photon/worker.py

This is probably a good illustrative migration from the old api to the new api. A few things @xlu451 to notice:
- we should add the deprecated warning lines in the old leptonai/api/*.py, in this case kv.py.
- For all the cli, if you encounter `explain_response` or old school `if res.ok` or other try-catch phrases of earlier APIs, let's delete them for the sake of clean code. Exceptions from the new style API should already be good enough to convey a meaningful message.
- for the rest of CLI commands, most of them do not come with a top level wrapper class (in this case lepton.kv.KV), other than queue and object store. Just FYI.
Tested: leptonai/tests/test_kv.py although this isn't a specific API test. We should add API tests down the road.

chore(cli): migrate the kv cli and kv wrapper class to the new API.

---

leptonai/photon/photon.py
leptonai/photon/tests/test_photon_should_not_override_init.py

This was encountered by one user so I figured we should add this guard.

feat(sdk): guard the __init__ function in case someone accidentally wrote __init__ instead of init

---

leptonai/cli/photon.py

Manually tested to make sure things are now working right.
The previous bug made the mount and env missing if launched from cli.

fix(sdk): variable names in the list is wrong

---

leptonai/api/v1/types/photon.py
leptonai/cli/deployment.py
leptonai/cli/photon.py
leptonai/cli/util.py
leptonai/config.py
leptonai/photon/tests/utils.py

Also to sanitize, `lep photon run --local` is routed to `lep photon runlocal`. `lep photon run` is now an alias of `lep deployment create`.

feat(cli): add lep dep create, and allow arbirary image and command

---

leptonai/cli/deployment.py

It seems our deployment create function will have
- deployment_template has not been declared error
- Deployment creation failed due to the mixed-use of 'name', 'photon', and 'photon(obj)'.
**Which seems led to our deployment create function not being usable at this time.**

fix: deployment create error

---

pyproject.toml

The recent upgrade of Ruff (10 hours ago) caused our linting process to fail, as it started checking .ipynb files in the leptonai/example project.

fix: lock ruff version

---

leptonai/config.py
leptonai/photon/photon.py

When a user creates a Photon class and passes parameters such as **request, cancel_on_connect_interval, or callback,** a multiple values error occurs 
Because these parameters are already defined in the **photon/photon.py: handle_request** function, which accepts them as parameters along with *args and **kwargs

fix: photon multiple values for argument request error

---

leptonai/api/v1/types/deployment.py
leptonai/api/v1/types/job.py

Backend introduced new 'stopping' and 'stopped' states, causing a crash on deployment list. 
Quick fix by adding the new states and decoupling them from the enum class. 
Tao will add a new field for this change, and we will follow up accordingly
Will also add an end-to-end test for this case.

fix：deployment list crush caused by new state

---

leptonai/client.py

From ticket
```
File "/opt/lepton/venv/lib/python3.10/site-packages/leptonai/client.py", line
423, in _generator
self._raise_for_detailed_status(res)
File "/opt/lepton/venv/lib/python3.10/site-packages/leptonai/client.py", line
411, in _raise_for_detailed_status
detail = res.text
File "/opt/lepton/venv/lib/python3.10/site-packages/httpx/_models.py", line
574, in text
content = self.content
File "/opt/lepton/venv/lib/python3.10/site-packages/httpx/_models.py", line
568, in content
raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without
having called `read()`.
```

fix: handling for streaming responses in leptonai.client.py._generator

---

pyproject.toml

Fixed httpx version to 0.28.0 and transformers version to address CI errors. Refer to the error messages in the CI tests for ‘fix httpx to 0.28.0’ and ‘fix httpx to 0.27.2’ for more details.

fix: respx mock error and mps oom

---

leptonai/cli/deployment.py
leptonai/cli/job.py

When creating endpoints using `lep endpoint create --file spec.json`, the `mounts` and `envs` arrays defined in the JSON spec file were being completely ignored, resulting in endpoints with `"mounts": null` and `"envs": null` even when properly configured in the input file.
In `leptonai/cli/deployment.py`, the code was **unconditionally overwriting** `spec.envs` and `spec.mounts` with values derived from CLI arguments, regardless of whether CLI arguments were provided:
```python
spec.envs = make_env_vars_from_strings(env_list, secret_list)
spec.mounts = make_mounts_from_strings(mount_list)
```
Modified the logic to only override spec values when CLI arguments are actually provided:
```bash
lep endpoint create --file spec.json --name test
```
```bash
lep endpoint create --file spec.json …
```

JSON spec mounts and envs being ignored in `lep endpoint create --file`

---

leptonai/cli/deployment.py

Only set `api_tokens` and `image_pull_secrets` when CLI arguments are provided or when no config file is loaded, preserving existing values from loaded files

fix: conditionally override deployment config tokens and secrets

---

example_usage.md
leptonai/api/v1/deployment.py
leptonai/api/v1/types/auth.py
leptonai/api/v1/types/deployment.py
leptonai/api/v1/types/ingress.py
leptonai/cli/deployment.py

backend MR: https://gitlab-master.nvidia.com/dgxc-lepton/lepton/-/merge_requests/189
UI MR: https://gitlab-master.nvidia.com/dgxc-lepton/lepton/-/merge_requests/321
public documentation: https://jirasw.nvidia.com/browse/LEP-2061
**Testing:**
Public
```
(.venv) dtzeng@dtzeng-mlt ~/workplace/leptonai % lep endpoint create \
--resource-shape gpu.h100-sxm \
--node-group heimdall-dev \
--autoscale-down 1,9999999 \
--container-image nvcr.io/nvidia/nemo:25.07 \
--container-port 8080 \
--container-command 'sleep infinity' \
--queue-priority 4 \
--public \
--log-collection true \
--name dtzeng-public1
/Volumes/workplace/leptonai/leptonai/api/v1/types/deployment.py:308: UserWarning: You might be using an out of date SDK. consider updating.
warnings.warn("You might be using an out of date SDK. …
```

feat: add support for ip whitelists for endpoints
