leptonai/leptonai

- leptonai/photon/hf/hf.py
```
(lepton) ➜  sdk git:(yqcli) ✗ lep photon run -n t2i -m hf:lllyasviel/ControlNet-v1-1
Failed to create photon: Unsupported Huggingface model: "hf:lllyasviel/ControlNet-v1-1" (the model did not specify a task).
Usually, this means that the model creator did not intend to publish the model as a pipeline, and is only using HuggingFace Hub as a storage for 
the model weights and misc files. Thus, it is not possible to run the model automatically. This is not a bug of Lepton SDK, but rather a limitation
of the hf ecosystem.
As a possible solution, you can try to access the corresponding model page at https://huggingface.co/lllyasviel/ControlNet-v1-1 and see if the 
model creator provided any instructions on how to run the model. You can then wrap this model into a custom Photon with …
```
> chore(sdk): add more useful error info for hf photon

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/support-hf-task-type.md
Added templates for feature request and hf task support request
> Update issue templates

- leptonai/api/deployment.py
- leptonai/api/types.py
- leptonai/cli/deployment.py
- leptonai/cli/photon.py
> feat(cli): allow lep dep update to use timeout

- leptonai/cli/photon.py
- leptonai/photon/tests/test_photon_cli.py
e.g. `lep run -n baichuan --model hf:baichuan-inc/Baichuan2-7B-Chat`
> Alias top level subcommand `lep run` to `lep photon run`

- .flake8
- leptonai/api/deployment.py
- leptonai/api/photon.py
- leptonai/api/util.py
- leptonai/api/workspace.py
- leptonai/cli/deployment.py
- leptonai/cli/photon.py
- leptonai/cli/workspace.py
- leptonai/cloudrun/remote.py
- leptonai/cloudrun/tests/test_cloudrun.py
This relies on 0.10.0 release from the infra side to be actually safe (w/ the timeout feature).
tested: manually ran `python leptonai/cloudrun/tests/test_cloudrun.py`
> feat(cli): make cloudrun actually usable.

- leptonai/cli/photon.py
- leptonai/config.py
- leptonai/photon/hf/hf_utils.py
- leptonai/photon/prebuilt/__init__.py
- leptonai/photon/prebuilt/vllm.py
`MODEL=codellama/CodeLlama-7b-Instruct-hf lep run -n codellama -m leptonai.photon.prebuilt.vLLM`
> feat: Add vLLM photon as prebuilt

- leptonai/photon/hf/hf.py
- leptonai/photon/hf/hf_utils.py
- leptonai/photon/util.py
- leptonai/registry.py
Tested with:
```
lep photon run -n vit -m hf:google/vit-base-patch16-224
```
> feat(hf): my own exercise to add image classification pipeline

- leptonai/photon/hf/hf.py
> chore(hf): add hf download folder info

- leptonai/config.py
- leptonai/photon/hf/hf.py
- leptonai/photon/tests/test_hf.py
So that local invocation and remote invocation are the same (`ph.run(...)`)
> Rename huggingface photon run_handler function name to run

- leptonai/client.py
- leptonai/photon/tests/test_client.py
closes https://github.com/leptonai/lepton/issues/3367
> fix(cli): more helpful message during client fail

- leptonai/cloudrun/remote.py
Between deployment ready and client ready, sometimes a 503 server not ready is returned. In this case, we will catch the connection error and simply retry.
> fix(cloudrun): catch exceptions when the client receives 503

- leptonai/photon/__init__.py
- leptonai/photon/prebuilt/__init__.py
- leptonai/photon/tests/test_photon_cli.py
- leptonai/photon/tests/test_vllm.py
- leptonai/photon/vllm/__init__.py
- leptonai/photon/vllm/vllm.py
- requirements.txt
`lep ph run -n mistralai -m vllm:mistralai/Mistral-7B-Instruct-v0.1`
> feat: assign prebuilt schema "vllm:" to vllm photon

- leptonai/photon/hf/hf.py
- leptonai/photon/hf/hf_utils.py
- leptonai/photon/tests/test_photon_cli.py
e.g.
`lep ph run -n baai-bge-large-en -m hf:BAAI/bge-large-en`
> feat: add support to hf feature extraction models

- leptonai/cli/photon.py
closes https://github.com/leptonai/lepton/issues/3942
> fix(cli): add available types to cli helpstr

- leptonai/cli/photon.py
- leptonai/photon/tests/test_client.py
- leptonai/photon/tests/test_client_docgen.py
- leptonai/photon/tests/test_types.py
- leptonai/photon/tests/utils.py
- leptonai/util/__init__.py
- leptonai/util/util.py
it's often needed in photons that needs to run core component in a subprocess and communicate through localhost:port
> feat: move util function find_available_port to leptonai.util

- leptonai/cli/photon.py
so that we can support vcs repo develop install
> fix: switch cwd to vcs checkout path during prepare

- leptonai/config.py
this version is for testing only
> feat: build 0.11.2 images with a lot of experimental features

- leptonai/photon/background.py
> fix: only print background task name in debug log (cont.)

- leptonai/client.py
Since the client often uses FileParam, we import it from photon in the client module as well.
current() and local() are aliased as class methods in the Client model, so users can do e.g.
```
from leptonai.client import Client
c = Client(Client.local())
```
> chore(client): import FileParam in client, and put current and local in Client.

- leptonai/util/s3cache.py
- leptonai/util/tests/test_s3cache.py
Manually tested with leptonai/util/tests/test_s3cache.py
> feat(sdk): add S3 file check

- leptonai/cli/photon.py
Closes https://github.com/leptonai/lepton/issues/3940
> fix(sdk): better local check for photon run with secret

- leptonai/cli/deployment.py
tested: manually tested in latest.
> fix(cli): show container name if deployment is an arbitrary container

- leptonai/api/photon.py
- leptonai/api/types.py
- leptonai/cli/deployment.py
- leptonai/cli/photon.py
Depends on https://github.com/leptonai/leptonai/pull/156
> feat(sdk): add gpu scaling options

- leptonai/api/deployment.py
- leptonai/api/photon.py
- leptonai/cli/photon.py
- leptonai/cloudrun/remote.py
- leptonai/cloudrun/tests/test_cloudrun.py
- leptonai/photon/photon.py
Related backend PR: https://github.com/leptonai/lepton/pull/4494
This PR also combined a legacy cleaning (no version check for 0.10.0 needed any more as we have moved beyond that)
> feat(sdk): support metadata.json in photon run

- leptonai/api/connection.py
- leptonai/api/kv.py
- leptonai/api/photon.py
- leptonai/api/util.py
- leptonai/api/workspace.py
- leptonai/kv.py
- leptonai/tests/test_kv.py
manually tested: `python leptonai/tests/test_kv.py`
> feat(kv): add kv client wrapper 

- leptonai/api/queue.py
- leptonai/queue.py
- leptonai/tests/test_queue.py
manually tested: `python leptonai/tests/test_queue.py` on latest.
> feat(queue): add queue capabilty to sdk

- leptonai/api/types.py
- leptonai/cli/secret.py
- leptonai/config.py
Depends on https://github.com/leptonai/lepton/pull/4546/files
> fix(sdk): loosen environmental variable naming rule

- CONTRIBUTING.md
> fix: update CONTRIBUTING.md clone address

- leptonai/photon/batcher.py
- leptonai/photon/photon.py
- leptonai/photon/tests/test_photon.py
- leptonai/photon/tests/utils.py
- leptonai/util/util.py
- requirements.txt
to avoid blocking other handler functions
> feat: add timeout for handler function

- leptonai/photon/photon.py
- leptonai/photon/tests/test_photon_empty_response.py
And we should really refactor typed_handler...
> chore(sdk): allow empty return to have 204 code

- leptonai/photon/photon.py
- leptonai/photon/tests/test_photon_cancel_on_disconnect.py
- leptonai/util/cancel_on_disconnect.py
Test yet to be written, but shooting a quick pr for you to take a look @bddppq 
Update: added test!
> [wip] feat(photon): cancel on disconnect for handler functions.

- leptonai/photon/photon.py
Found this when updating imgpilot with @vthinkxie
> chore(photon): add cloudpickle version check

- leptonai/client.py
- leptonai/photon/tests/test_client.py
- leptonai/photon/tests/utils.py
Also closes https://github.com/leptonai/leptonai/issues/103
> feat(client): add client timeout feature, and more test on cancel_on_disconnect together with client.

- leptonai/photon/dockerfiles/photon-py.Dockerfile
> use tcmalloc to avoid memory leak in webui

- leptonai/cli/photon.py
Sometimes when there are libraries a, b and c specified and if c's build is dependent on a and b, the default behavior (installing all at once) will trigger an error. This is because pip does building all first, and then install all.
In this case, this fix will provide a fallback path where we install the packages in the order the user specified. If it still triggers a failure, this won't be any worse - just another round trying.
> fix(sdk): allow pip install to be done sequentially

- leptonai/cli/photon.py
This is equivalent to lep dep remove and then again doing lep photon run.
> chore(sdk): add a --rerun arg to lep photon run

- leptonai/photon/vllm/vllm.py
This helps us building photon templates with minimal code in the frontend.
> feat(vllm): Adaptively update deployment template according to model string

- leptonai/api/photon.py
- leptonai/api/types.py
- leptonai/cli/photon.py
Also related (internal): https://github.com/leptonai/lepton/issues/4888
> feat(sdk): add public photon support

- leptonai/photon/tests/test_vllm.py
- leptonai/photon/vllm/vllm.py
https://github.com/vllm-project/vllm/pull/2046
> update transformers version requirement for running mixtral in vllm

- leptonai/photon/vllm/vllm.py
model downloading can take long time
> Use separted health_check_liveness_tcp_port in vllm photon

- leptonai/api/types.py
- leptonai/cli/cli.py
- leptonai/cli/deployment.py
- leptonai/cli/pod.py
> feat(cli): add pod support

- leptonai/templates/sd_farm_by_lepton/README.md
- leptonai/templates/sd_farm_by_lepton/__init__.py
> feat(template): add sd_farm

- leptonai/__init__.py
- leptonai/kv.py
- leptonai/objectstore.py
- leptonai/templates/stable_video_diffusion/svd.py
- leptonai/tests/test_kv.py
- leptonai/tests/test_objectstore.py
- leptonai/util/util.py
Mainly modified from JJ's code, but:
- used the new ObjectStore class to wrap object store operations.
- updated the kv and object store interface a bit to make it more user friendly.
> chore(template): add svd example

- leptonai/kv.py
- leptonai/photon/photon.py
- leptonai/tests/test_kv.py
Since a newly created kv still suffers a bit from the server dns propagation problem, this adds a few checks so we can be more tolerant to it.
> chore(kv): guard kv more

- leptonai/photon/photon.py
When use raw args, we don't use the request_model, and passing the args to request_model usually leads to an error. This fixes it.
> chore(sdk): fix use_raw_args

- leptonai/photon/photon.py
- leptonai/photon/tests/test_photon.py
it's number of currently processing + waiting to be processed requests
> Expose uvicorn server #tasks at /queue-size

- leptonai/config.py
- leptonai/photon/photon.py
This reverts commit 246a3a1fd7c60696f3fbda73e6d426cce6567f83.
> Revert "feat: default photon server keep_alive idle timeout to 30mins (#262)

- CONTRIBUTING.md
- pyproject.toml
- update python version range 
- update install script with quote to fit zsh shell 
[@Yangqing note: closes #283 ]
> chore(setup): update python version range limitation, update install script with quote to fit zsh env

- misc/benchmark/run.py
e.g.
`python misc/benchmark/run.py -r 4 -c 1,2,4,8,16 --max-tokens 150`
> feat: support specify multiple concurrent requests values in one run

- leptonai/config.py
- leptonai/photon/photon.py
This reverts commit d5a7079b2169163fc5113959783f7c8b9ce6d568.
> Revert "Revert "feat: default photon server keep_alive idle timeout to 30mins (#262)" (#280)"

- leptonai/config.py
- leptonai/photon/dockerfiles/photon-py.Dockerfile
- leptonai/photon/dockerfiles/photon-rocm-py.Dockerfile
Update torch version to latest 2.2.0
> release: 0.17.0

- README.md
Change "python" to "Python" to make it more formal :)
> Update README: python -> Python

- leptonai/cli/storage.py
When I run `lep --help`, I found the typo:
> chore: storrage to storage

- misc/benchmark/run.py
- misc/benchmark/sonnet.txt
Also added:
- warmup
- support using (non-chat) completion
- print response (for debug model response quality)
> Support specifying prompt length in benchmark

- leptonai/api/photon.py
(we actually already use it to manage public photons)
> fix(sdk): public photon deletion now supported.

- leptonai/api/types.py
- leptonai/cli/job.py
- added workers config
- added default image
- added `ttl_seconds_after_finished`
closes https://github.com/leptonai/lepton/issues/6047
closes https://github.com/leptonai/lepton/issues/6048
Related to (but not closing) https://github.com/leptonai/lepton/issues/6001
> feat(job): complete the job arguments per the new spec.

- requirements.txt
rate limiter was removed in #196
> remove limits from python dep

- leptonai/client.py
The backend already supports this, so we can change the client code now.
> feat(photon): use full url for deployment endpoints, instead of the earlier header field

- leptonai/photon/hf/hf.py
- leptonai/photon/hf/hf_utils.py
Tested: https://huggingface.co/microsoft/llmlingua-2-bert-base-multilingual-cased-meetingbank
> feat(hf): support token-classification

- leptonai/photon/tests/test_worker.py
- leptonai/photon/worker.py
> fix: run on_task in parallel with worker_max_concurrency

- leptonai/cli/photon.py
It does abuse the class member variables a little bit - by manipulating it during runtime. But, since the deployment only installs requirement dependencies from the metadata, and metadata is recorded during creation time, I believe this should be always correct... @bddppq kindly take a look?
> feat(cli): add a functionality to allow specifying additional dependencies

- leptonai/config.py
This is just to catch up with the current list of proper shapes. No functionality change introduced.
> chore(config): add proper resource shapes

- leptonai/api/deployment.py
- leptonai/api/photon.py
- leptonai/api/types.py
closes https://github.com/leptonai/lepton/issues/6221
> feat(cli): update deployment spec to match recent system updates

- leptonai/api/job.py
- leptonai/cli/job.py
- leptonai/cli/util.py
This should meet @bobmayuze 's need for the customers.
Internally - I am also conforming to the formatting we are planning here https://github.com/leptonai/lepton/issues/8548 with @vthinkxie .
cc'ing @bddppq and @xlu451 for review.
> chore(cli): migrate the job cli to new api format

- leptonai/api/v1/types/deployment_operator_v1alpha1/deployment.py
We will need to coordinate with the frontend and infra release, but put it out here for now.
> chore(sdk): coordinated name change

- leptonai/api/v1/client.py
- leptonai/api/v1/deployment.py
- leptonai/api/v1/pod.py
This is kinda needed for the upcoming fastgpu usage (if people want to use api). It's basically a wrapper over deployment but with its own constraints.
> feat(api): add pod api

- leptonai/api/v1/job.py
- leptonai/api/v1/types/events.py
- leptonai/api/v1/workspace_record.py
- leptonai/cli/job.py
- leptonai/cli/photon.py
- conducted end-to-end (E2E) testing for photon-cli.
- conducted manual test for job-cli.log
> Add photon cli

- leptonai/config.py
- leptonai/photon/photon.py
- leptonai/photon/tests/test_photon.py
customizable via environment variable LEPTON_ALLOW_ORIGINS (at runtime)
> feat: allow all origins by default

- leptonai/api/v1/client.py
- leptonai/api/workspace.py
- leptonai/cli/cli.py
- leptonai/cli/workspace.py
- leptonai/photon/hf/hf.py
WIP: waiting for 404 error test case
> fix: workspace init user hint

- leptonai/api/v0/photon.py
- leptonai/cli/deployment.py
- leptonai/cli/photon.py
- leptonai/cloudrun/remote.py
- leptonai/config.py
Something that we need to ship for user convenience so I went ahead and changed it.
> feat(sdk): add environmental variable LEPTON_DEFAULT_RESOURCE_SHAPE

- leptonai/cli/deployment.py
- leptonai/cli/job.py
- leptonai/cli/pod.py
- leptonai/cli/util.py
Add node group option for job and pod
> feat: add node group option

- leptonai/cli/deployment.py
**Introducing new autoscale options**
'-r'
'--replicas_static <replica_number>' 
'-ad'  
'--autoscale-down <replica_number>,<timeout>' 
'-agu'
'--autoscale-gpu-util <min_replica>,<max_replica>,<gpu-util-threshold>' 
'-aq'
'--autoscale-qpm <min_replica>,<max_replica>,<qpm-threshold>'
> refactor: autoscale options

- leptonai/api/v1/types/common.py
> feat: support both integer and string formats for metadata version

- leptonai/templates/llm_by_lepton/README.md
(added by @Yangqing ): closes #465
> chore(docs): update chat template usages

- misc/benchmark/run.py
- support fractional qps
- get usage__info in streaming requests
- table formatted output
> update llm benchmark script

- leptonai/photon/tests/test_photon_cli.py
- pyproject.toml
Fix CI test failures caused by torch 2.5.1.
> fix: ci test failures with torch 2.5.1 compatibility

- leptonai/api/v1/job.py
- leptonai/api/v1/types/common.py
Signed-off-by: Zhiting Zhu <zhitingz@lepton.ai>
> chore(job): add labels field; add API to query job via labels

- leptonai/photon/dockerfiles/photon-aigc.Dockerfile
- leptonai/photon/dockerfiles/photon-py.Dockerfile
This reverts commit 558663bd4cbc1b53962c1eb6971b542501ee7589.
> Revert "Update cuda base image and torch version (#552)"

- leptonai/config.py
https://github.com/leptonai/leptonai/actions/runs/14078360531
> release: 0.23.0

- leptonai/photon/photon.py
- pyproject.toml
fix(pickle): recreate anyio.Semaphore in __setstate__ to resolve load error on anyio > 4.4.0
> fix: pickle-anyio-semaphore

- leptonai/cli/deployment.py
- leptonai/cli/job.py
- leptonai/cli/pod.py
- leptonai/cli/util.py
> feat(cli): add shared nodegroup/queue/reservation handling

- leptonai/cli/node.py
- leptonai/cli/tests/test_node_cli.py
Updated the node group filtering logic to ensure deduplication of node groups when multiple filters match
> fix: improve node group filtering in list command
